### ISSUE TITLE
Controle do led usando pinos relay.

### ISSUE THREAD

**Issue by Bucket7033** [Da-was/Roosters7033#13]
1. Adicionar estrutura pra controle dos leds no robô usando os pinos relay da placa.
2. Adicionar mudanças de cor baseadas nas ações do robô.
3. Criar interface para mudar a cor do robô.

**Comment by Da-was** [comment]
Trabalhando na classe pra controle dos leds.

**Comment by Da-was** [comment]
Commit feito com classe trabalhada. Falta testar.
