### ISSUE TITLE
Documentar código

### ISSUE THREAD

**Issue by Da-was** [Da-was/Roosters7033#6]
Deixar o código mais legível e didático para que outras pessoas consigam entender.

**Comment by Da-was** [comment]
Fizemos parte hoje, a ana ira terminar de tarde.

**Comment by Bucket7033** [comment]
Boa parte do código está documentada, falta apenas preservar os comentários da master

**Comment by Bucket7033** [comment]
Vamos dar merge no código hj, vai ficar do jeito que está para preservar história.
